In [1]:
##################################################################################################################
#                                                                                                                #
#                                                   borrador                                                     #
#                                                                                                                #
##################################################################################################################

In [8]:
# Librerias:
import numpy as np
import matplotlib.pyplot as plt

# Resumen de los objetivos:
* plantear númericamente el ***potencial eléctrico*** en distribuciones continuas.
* calcular el ***campo eléctrico*** mediante el gradiente.
* Resolver ec. fundamental de poisson.  

### Ecuación de Poisson
La relación entre el potencial y la densidad de carga es:
$$\vec{\nabla}^2 \phi(\mathbf{r}) = -\frac{\rho(\mathbf{r})}{\varepsilon_0}$$

### Relación Campo electrico y Potencial

$$\vec{E} = -\vec{\nabla} \phi  $$


In [3]:
# Maya regular (caso 2D)

# Valor de constantes
e_0 = 8.854e-12 #C^2/N m

# Parámetros a definir primero a 2D
mx, my = 50, 50
# definir espacio (Definir el por qué se calculan los espacios asi con alguna posible analogía para entender mejor el concepto de discretizar).
Lx, Ly = 1, 1
dx, dy = Lx/(mx-1), Ly/(my-1)
# El paso se calcula de la siguiente manera porque

# Maya 3D
mz = 50
Lz = 1
dz= Lz/(mz-1)


In [4]:
rho = np.zeros((mx,my))
print(rho)
rho3D = np.zeros((mx,my,mz))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
laplaciano2D = np.zeros_like(rho)

for i in range(1, mx - 1):
    for j in range(1, my - 1):
        termino_x = (rho[i+1,j] - 2 * rho[i,j] + rho[i-1,j]) / dx**2
        termino_y = (rho[i,j+1] - 2 * rho[i,j] + rho[i,j-1]) / dy**2
        laplaciano2D[i,j] = termino_x + termino_y
print(laplaciano2D)

#---------------------------------------------------------------------------

laplaciano3D = np.zeros_like(rho3D)

for i in range(1, mx - 1):
    for j in range(1, my - 1):
        for k in range(1, mz-1):
            termino_x = (rho3D[i+1,j,k] - 2 * rho3D[i,j,k] + rho3D[i-1,j,k]) / dx**2
            termino_y = (rho3D[i,j+1,k] - 2 * rho3D[i,j,k] + rho3D[i,j-1,k]) / dy**2
            termino_z = (rho3D[i,j,k+1] - 2 * rho3D[i,j,k] + rho3D[i,j,k-1]) / dz**2
            laplaciano3D[i,j,k] = termino_x + termino_y + termino_z
print(laplaciano3D)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0.

In [9]:
# Condiciones de frontera:
# El potencial de por si, debe tender a 0 en el infinito, para nuestro problema, diremos que el potencial vale 0 en los bordes de la cuadricula

# Se establece un valor fijo en cada borde de la maya como condición de borde para el potencial
rho[0,:] = rho[-1,:] = rho[:,0] = rho[:,-1] = 20
rho

array([[20., 20., 20., ..., 20., 20., 20.],
       [20.,  0.,  0., ...,  0.,  0., 20.],
       [20.,  0.,  0., ...,  0.,  0., 20.],
       ...,
       [20.,  0.,  0., ...,  0.,  0., 20.],
       [20.,  0.,  0., ...,  0.,  0., 20.],
       [20., 20., 20., ..., 20., 20., 20.]], shape=(50, 50))

In [10]:
# Grafico círculo en 2D

def circle(x,y):
    return x**2 + y**2
    